### ISSUE TITLE
bind wrapper does not check for address family

### ISSUE THREAD

**Issue by marmarek** [yongboy/bindp#5]
Bind wrapper assume AF_INET address family, [here](https://github.com/yongboy/bindp/blob/master/bindp.c#L114):
```
 lsk_in = (struct sockaddr_in *)sk;
```
If given socket is something different (like AF_UNIX), this may lead to various errors, from bind syscall failures (invalid address value in sockaddr structure), to memory corruption (writing outside of structure), with potentially some security implications.

**Comment by yongboy** [comment]
Good PR :))
